pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                echo "Building...!!"
                sh '/var/jenkins_home/workspace/api-python/flask/build.sh'
            }
        }
        stage('Test'){
            steps {
                echo "Testing...!!"
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying...!!"
                sh '/var/jenkins_home/workspace/api-python/flask/deploy.sh'
            }
        }
    }
}
