pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                echo "Building...!!"
                sh 'ls -l'
                sh './flask/build.sh'
            }
        }
        stage('Test'){
            steps {
                echo "Testing...!!"
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying...!!!"
                sh './flask/deploy.sh'
            }
        }
    }
}
